cc_library(
    name = "common",
    srcs = [
    ],
    hdrs = [
        "common_grammar.h",
        "common_types.h",
        "parser_base.h",
        "parser_state.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@taocpp_pegtl//:pegtl",
    ],
) 