cc_test(
    name = "message_parser_test",
    srcs = ["message_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:message_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "message_transmitters_parser_test",
    srcs = ["message_transmitters_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:message_transmitters_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "signal_parser_test",
    srcs = ["signal_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:signal_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "signal_group_parser_test",
    srcs = ["signal_group_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:signal_group_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "signal_type_def_parser_test",
    srcs = ["signal_type_def_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:signal_type_def_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "signal_value_type_parser_test",
    srcs = ["signal_value_type_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/message:signal_value_type_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 