cc_test(
    name = "environment_variable_parser_test",
    srcs = ["environment_variable_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/environment:environment_variable_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "environment_variable_data_parser_test",
    srcs = ["environment_variable_data_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/environment:environment_variable_data_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 