cc_test(
    name = "attribute_definition_parser_test",
    srcs = ["attribute_definition_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/attribute:attribute_definition_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "attribute_definition_default_parser_test",
    srcs = ["attribute_definition_default_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/attribute:attribute_definition_default_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "attribute_value_parser_test",
    srcs = ["attribute_value_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/attribute:attribute_value_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 