load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "dbc_types",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"], allow_empty = True),
) 