cc_test(
    name = "value_table_parser_test",
    srcs = ["value_table_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/value:value_table_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "value_description_parser_test",
    srcs = ["value_description_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/value:value_description_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 