cc_test(
    name = "dbc_file_parser_test",
    srcs = ["dbc_file_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser:dbc_file_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 