load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "simple_parser",
    srcs = ["simple_parser.cc"],
    deps = [
        "//:dbc_parser",
    ],
) 