cc_test(
    name = "version_parser_test",
    srcs = ["version_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/base:version_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "new_symbols_parser_test",
    srcs = ["new_symbols_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/base:new_symbols_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "bit_timing_parser_test",
    srcs = ["bit_timing_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/base:bit_timing_parser",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "nodes_parser_test",
    srcs = ["nodes_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/base:nodes_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 