cc_test(
    name = "comment_parser_test",
    srcs = ["comment_parser_test.cc"],
    deps = [
        "//src/dbc_parser/parser/comment:comment_parser",
        "@com_google_googletest//:gtest_main",
    ],
) 